---
- name: Install pip
  apt:
    update_cache: yes
    package: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: Pip install supervisor
  pip:
    name: supervisor
    state: present
    extra_args: --pre
    version: "{{ supervisor_version }}"

- name: Create necessary logfile directory for supervisord
  file:
    state: directory
    path: "{{ supervisor_supervisord_log_path }}"
    owner: "{{ supervisor_owner}}"
    group: "{{ supervisor_group }}"

- name: Install the supervisor configuration file
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
    owner: "{{ supervisor_owner }}"
    group: "{{ supervisor_group }}"
  notify: restart supervisor

- name: Install the supervisor init script
  template:
    src: supervisor_initd.j2
    dest: /etc/init.d/supervisor
    mode: 0755
    owner: "{{ supervisor_owner }}"
    group: "{{ supervisor_group }}"
  notify: restart supervisor

- name: Ensure the supervisor service is running
  service:
    name: supervisor
    state: started
    enabled: yes
